Repository amazon-connect/amazon-connect-chatjs, pull requests merged in 2024-03, with the labels that each got.

#196 fix: .onConnectionEstablished() is fired twice after invoking .connect(); closes 124
  src/core/chatController.js
  src/core/chatController.spec.js
Labels: 🐛 Bug

#194 fix: enable message receipts by default; closes #132
  src/constants.js
  src/core/chatController.spec.js
  src/core/chatSession.js
  src/globalConfig.js
  src/globalConfig.spec.js
Labels: 🐛 Bug

#212 update CHANGELOG for 2.2.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 📝 Documentation, Dependencies

#211 Create COMMON_ISSUES.md doc
  .github/docs/COMMON_ISSUES.md
Labels: 📝 Documentation
